import { TECH } from '@/content/sections/TechStack';
import SurfCommunity from '@/public/images/projects/surf-community.png';
import MyQuiver from '@/public/images/projects/my-quiver.png';

export const PROJECTS = [
  {
    name: 'Lunatag',
    type: ['Shopify Apps'],
    tech: [
      TECH.typescript,
      TECH.vercel,
      TECH.nextjs,
      TECH.reactjs,
      TECH.prisma,
    ],
    url: 'https://apps.shopify.com/lunatag',
    repository: '',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2022',
  },
  {
    name: 'Tellmann',
    type: ['Marketing Sites'],
    tech: [TECH.typescript, TECH.vercel, TECH.nextjs, TECH.reactjs],
    url: 'https://tellmann.co.za',
    repository: 'https://github.com/FelixTellmann/tellmann.co.za',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2020',
  },
  {
    name: 'ClickUpload',
    type: ['Shopify Apps'],
    tech: [
      TECH.typescript,
      TECH.vercel,
      TECH.nextjs,
      TECH.reactjs,
      TECH.tailwind,
      TECH.prisma,
    ],
    url: 'https://apps.shopify.com/click-upload',
    repository: '',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2021',
  },
  {
    name: 'Plant Sitting (MVP)',
    type: ['React Native'],
    tech: [TECH.react_native, TECH.expo, TECH.expressJS, TECH.mongoDB],
    description: `Une application mobile de mise en réseau pour le gardiennage des plantes.`,
    featuredImage: SurfCommunity,
    repository: 'https://github.com/ByronMike/plantsitting-frontend',
    year: '2022',
  },
  {
    name: 'My quiver (MVP)',
    type: ['No code'],
    tech: [TECH.no_code, TECH.glide, TECH.excel],
    description: `My Quiver est une app mobile permettant aux Surfeurs de créer un quiver virtuel.`,
    featuredImage: MyQuiver,
    year: '2020',
    repository: '',
    url: 'https://myquiver.glideapp.io/',
  },
  {
    name: 'Surf-community.fr',
    type: ['Wordpress'],
    tech: [TECH.wordpress, TECH.linux, TECH.apache, TECH.mysql],
    description: `Surf Community est un site dédié à la communauté Surf (+300k vues).`,
    featuredImage: SurfCommunity,
    year: '2017',
    repository: '',
    url: 'https://surf-community.fr/',
  },
];
