import { TECH } from '@/content/sections/TechStack';
import SurfCommunity from '@/public/images/projects/surf-community.png';

export const PROJECTS = [
  {
    name: 'Lunatag',
    type: ['Shopify Apps'],
    tech: [
      TECH.typescript,
      TECH.vercel,
      TECH.nextjs,
      TECH.reactjs,
      TECH.prisma,
    ],
    url: 'https://apps.shopify.com/lunatag',
    repository: '',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2022',
  },
  {
    name: 'Tellmann',
    type: ['Marketing Sites'],
    tech: [TECH.typescript, TECH.vercel, TECH.nextjs, TECH.reactjs],
    url: 'https://tellmann.co.za',
    repository: 'https://github.com/FelixTellmann/tellmann.co.za',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2020',
  },
  {
    name: 'ClickUpload',
    type: ['Shopify Apps'],
    tech: [
      TECH.typescript,
      TECH.vercel,
      TECH.nextjs,
      TECH.reactjs,
      TECH.tailwind,
      TECH.prisma,
    ],
    url: 'https://apps.shopify.com/click-upload',
    repository: '',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2021',
  },
  {
    name: 'KidsLiving',
    type: ['Ecommerce Sites', 'Integrations'],
    tech: [TECH.typescript, TECH.vercel],
    url: 'https://kidsliving.co.za',
    repository: '',
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2017',
  },
  {
    name: 'Lunalemon',
    type: ['Marketing Sites'],
    tech: [TECH.typescript, TECH.tailwind, TECH.nextjs, TECH.vercel],
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2022',
    url: 'https://kidsliving.co.za',
    repository: 'https://github.com/FelixTellmann/lunalemon.dev',
  },
  {
    name: 'Lunalemoned',
    type: ['Marketing Sites'],
    tech: [TECH.typescript, TECH.tailwind, TECH.nextjs, TECH.vercel],
    description: `A random app about random things. And I add some descriptions just to add a new line.`,
    featuredImage: SurfCommunity,
    year: '2022',
    url: 'https://kidsliving.co.za',
    repository: 'https://github.com/FelixTellmann/lunalemon.dev',
  },
];
